using Microsoft.CodeAnalysis;
using System.Text;

namespace DouglasDwyer.FixedArray.Generator;

/// <summary>
/// Roslyn source generator that emits stack-allocated <c>Array1&lt;T&gt;</c> through
/// <c>Array32&lt;T&gt;</c> structs and the supporting <c>FixedArrayBuilder</c> class
/// at compile time.
/// </summary>
[Generator]
public class FixedArrayGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Registers a post-initialization output that emits all generated fixed-array
    /// source into <c>Arrays.g.cs</c>.
    /// </summary>
    /// <param name="context">The incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("Arrays.g.cs", GenerateSource());
        });
    }

    /// <summary>
    /// Builds the complete source text containing <c>Array1&lt;T&gt;</c> through
    /// <c>Array32&lt;T&gt;</c> and <c>FixedArrayBuilder</c>.
    /// </summary>
    /// <returns>The generated C# source text.</returns>
    private static string GenerateSource()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace DouglasDwyer.FixedArray");
        sb.AppendLine("{");

        for (var n = 1; n <= 32; n++)
            AppendArrayType(sb, n);

        AppendBuilder(sb);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Appends the <c>Array<paramref name="n"/>&lt;T&gt;</c> struct declaration to
    /// <paramref name="sb"/>, including its constructor, interface implementations,
    /// equality members, and operators.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append into.</param>
    /// <param name="n">The fixed element count for this array type (1–32).</param>
    private static void AppendArrayType(StringBuilder sb, int n)
    {
        var s = n == 1 ? "" : "s";

        sb.AppendLine($"    /// <summary>A stack-allocated array of {n} element{s}.</summary>");
        sb.AppendLine($"    /// <typeparam name=\"T\">The element type.</typeparam>");
        sb.AppendLine($"    [CollectionBuilder(typeof(FixedArrayBuilder), nameof(FixedArrayBuilder.Create{n}))]");
        sb.AppendLine($"    [InlineArray({n})]");
        sb.AppendLine($"    public struct Array{n}<T> : IFixedArray<T>, IEquatable<Array{n}<T>>, IReadOnlyList<T>");
        sb.AppendLine("    {");

        sb.AppendLine("        /// <summary>The number of elements in the array.</summary>");
        sb.AppendLine($"        public int Length => {n};");
        sb.AppendLine();
        sb.AppendLine("        private T _element0;");
        sb.AppendLine();

        // Constructor
        var paramDecls = BuildJoin(n, i => $"T e{i}");
        sb.AppendLine($"        /// <summary>Initializes an <see cref=\"Array{n}{{T}}\"/> with the given elements.</summary>");
        for (var i = 0; i < n; i++)
            sb.AppendLine($"        /// <param name=\"e{i}\">The <c>{i}</c>-index element.</param>");
        sb.AppendLine($"        public Array{n}({paramDecls})");
        sb.AppendLine("        {");
        sb.AppendLine("            _element0 = e0;");
        for (var i = 1; i < n; i++)
            sb.AppendLine($"            this[{i}] = e{i};");
        sb.AppendLine("        }");
        sb.AppendLine();

        // IEnumerable / IFixedArray
        sb.AppendLine($"        /// <inheritdoc cref=\"IEnumerable.GetEnumerator\"/>");
        sb.AppendLine($"        public FixedArrayEnumerator<T, Array{n}<T>> GetEnumerator() => new FixedArrayEnumerator<T, Array{n}<T>>(this);");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        IEnumerator<T> IEnumerable<T>.GetEnumerator() => GetEnumerator();");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        T IFixedArray<T>.Get(int i) => this[i];");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        T IReadOnlyList<T>.this[int i] => this[i];");
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        int IReadOnlyCollection<T>.Count => Length;");
        sb.AppendLine();

        // Equals
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public override bool Equals([NotNullWhen(true)] object? obj)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (obj is Array{n}<T> rhs) return this == rhs;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        public bool Equals(Array{n}<T> other) => this == other;");
        sb.AppendLine();

        // GetHashCode
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine("        public override int GetHashCode()");
        sb.AppendLine("        {");
        sb.AppendLine("            var hash = new System.HashCode();");
        sb.AppendLine($"            for (var i = 0; i < {n}; i++) hash.Add(this[i]);");
        sb.AppendLine("            return hash.ToHashCode();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // operator ==
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Compares two arrays element-by-element for equality.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static bool operator ==(Array{n}<T> lhs, Array{n}<T> rhs)");
        sb.AppendLine("        {");
        sb.AppendLine($"            for (var i = 0; i < {n}; i++)");
        sb.AppendLine("                if (!Equals(lhs[i], rhs[i])) return false;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // operator !=
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Compares two arrays element-by-element for inequality.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static bool operator !=(Array{n}<T> lhs, Array{n}<T> rhs) => !(lhs == rhs);");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends the <c>FixedArrayBuilder</c> internal static class to
    /// <paramref name="sb"/>. The class exposes <c>Create1</c> through
    /// <c>Create32</c> factory methods used by collection-expression support.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append into.</param>
    private static void AppendBuilder(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Provides collection expression support for fixed-size array types.</summary>");
        sb.AppendLine("    internal static class FixedArrayBuilder");
        sb.AppendLine("    {");

        for (var n = 1; n <= 32; n++)
        {
            var s = n == 1 ? "" : "s";
            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// Creates an <see cref=\"Array{n}{{T}}\"/> from a span of exactly {n} element{s}.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        /// <exception cref=\"System.ArgumentOutOfRangeException\">");
            sb.AppendLine($"        /// Thrown when <paramref name=\"items\"/> does not contain exactly {n} element{s}.");
            sb.AppendLine($"        /// </exception>");
            sb.AppendLine($"        public static Array{n}<T> Create{n}<T>(ReadOnlySpan<T> items)");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (items.Length != {n}) throw new System.ArgumentOutOfRangeException(nameof(items), \"Expected exactly {n} element{s}.\");");
            sb.AppendLine($"            var result = default(Array{n}<T>);");
            sb.AppendLine($"            for (var i = 0; i < {n}; i++) result[i] = items[i];");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            if (n < 32) sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Projects indices <c>0</c> through <c><paramref name="n"/> - 1</c> through
    /// <paramref name="selector"/> and returns the results joined by <c>", "</c>.
    /// </summary>
    /// <param name="n">The number of elements to project.</param>
    /// <param name="selector">A function that maps an index to a string fragment.</param>
    /// <returns>A comma-separated string of the projected fragments.</returns>
    private static string BuildJoin(int n, System.Func<int, string> selector)
    {
        var parts = new string[n];
        for (var i = 0; i < n; i++) parts[i] = selector(i);
        return string.Join(", ", parts);
    }
}
